### ISSUE TITLE
Call consumer.ConnectToNsqLookupd("192.168.1.10:4161") timeout exception

### ISSUE THREAD

**Issue by codeyu** [judwhite/NsqSharp#42]
Exception message:
timeout 00:00:01 exceed when dialing localhost.localdomain:4150

BUT,call **consumer.ConnectToNsqd("192.168.1.10:4150")** is OK.

**Comment by judwhite** [comment]
It looks like it's getting the connection to nsqlookupd, the address in the error message is an nsqd TCP port.

`localhost.localdomain` is probably the issue. Try running nsqd with the `-broadcast-address` flag with an address the other machine can reach.
