### ISSUE TITLE
Discovery nsqd

### ISSUE THREAD

**Issue by wpoPR** [judwhite/NsqSharp#44]
Hi, I'm using NsqSharp with Docker! and I'm trying to scale the nsqd. I'm able to do that. I'm using nsqlookupd for getting all nsqd instances, but, it returns me a strange IP and ports, and I can't use these in my clients.

Any ideia?

**Comment by judwhite** [comment]
Hi @wpoPR 

Are you setting the `--broadcast-address`? http://nsq.io/deployment/docker.html

```
docker run --name nsqd -p 4150:4150 -p 4151:4151 \
    nsqio/nsq /nsqd \
    --broadcast-address=<host> \
    --lookupd-tcp-address=<host>:<port>
```
