### ISSUE TITLE
How to batch handle messages

### ISSUE THREAD

**Issue by kevinleeTCA** [judwhite/NsqSharp#87]
Recently, I am using Nsq .NET library (Nsqsharp: https://github.com/judwhite/NsqSharp). It is very convenient to establish producer and consumer, but it seems that it can only handle one message per time, 

```
    var consumer = new Consumer("topic", "channel");
    consumer.AddHandler(new MessageHandler());
    consumer.ConnectToNsqLookupd("127.0.0.1:4161");

```
We can only handle message in the `HandleMessage` method defined in MessageHandler class

```
    private class MessageHandler : IHandler
        {
            public void HandleMessage(IMessage message)
            {
                var msgJson = Encoding.UTF8.GetString(message.Body);
                // then upload to cloud side
            }

            public void LogFailedMessage(IMessage message)
            {
                throw new NotImplementedException();
            }
        }

```
How can we batch like 100 messages and then upload them to cloud side at once ?
Send Http request for each of the message will be very expensive.

**Comment by judwhite** [comment]
Hi @kevinleeTCA 

If you want to take an optimistic approach you can batch them in memory and allow the handler to return after it's added to the in-memory queue. In this case the message will `FIN` when the handler returns.

If you want to wait until they're written to the service, I would send them to an in-memory queue and wait for a successful flush of the queue. From NsqSharp `Config` (passed to the `Consumer` constructor), set the `MaxInFlight` property to a value greater than 1. In the `consumer.AddHandler` call use the `threads` second parameter to use more threads to process incoming messages.

The reason both of these settings exist is `MaxInFlight` can be tuned to pull messages from `nsqd` and keep them waiting for a free handler thread. You can keep your thread count lower than `MaxInFlight` (if you want) if you call `message.DisableAutoResponse()` and allow the handler to return. In this case you'd call `message.Finish()` or `message.Requeue()` manually in your outside processing, and the `MaxInFlight` count considers messages which have not been `FIN`'d or `REQ`'d.

For example:
- `MaxInFlight = 100`
- `threads = 8` (if `threads = 100`, no need for the rest)
- Call `message.DisableAutoResponse()` in the handler before returning from the handler. Pass the `message` to your batching code.
- The batching code will call `message.Finish()` or `message.Requeue()`
- In this case, you won't have more than 100 messages in the batcher at a time, while still only using 8 threads to pull down messages.

This would be a good example to add to the `examples` directory. Thanks for bringing it up.

Any questions please let me know.
