### ISSUE TITLE
empty topic not working and requeue conunt 0

### ISSUE THREAD

**Issue by lifeRockss** [judwhite/NsqSharp#90]
Hi,

 we are reading a message on the topic and posting it to the 3rd party. currently, the 3rd party is not reachable hence we get a timeout and we are doing 
> message.requeue();

1) But the requeue count on `curl localhost:4151/stats?format=json` always shows 0 and timeout_count go up.
2) When we run `curl -v -X POST http://localhost:4151/topic/empty?topic=MYTOPIC` it has no impact and the message turns up to the consumer.

3) more of a question, is there any setting to tell NSQ to discard the message after a certain number of tries?

**Comment by judwhite** [comment]
@lifeRockss 1 and 2 are more questions for the NSQ team. If you try to requeue a timed out message (from nsqd's point of view) I think you'll get an E_REQ_FAILED:

https://github.com/nsqio/nsq/blob/e8833c16ce0aca974b1022ea49a6f8dadc603f0a/nsqd/protocol_v2.go#L735

RE: 2, I'm not sure if emptying a topic includes deferred/requeued messages. It seems like it should but I can't remember exactly how that works. cc: @mreiferson @jehiah @ploxlin

RE: 3, this is controlled at the client. NSQ increments the attempt count on the message. NsqSharp.Config has `MaxAttempts` to control how many times before it fails with MaxAttemptsExceeded:

https://github.com/judwhite/NsqSharp/blob/9fc164c367c744f39f6e9d8cba0313f8dd524102/NsqSharp/Config.cs#L220
